blueprint:
  name: Motion-activated Light with luminosity threshold
  description: Turn on a light when motion is detected in certain luminosity condition.
  domain: automation
  source_url: https://github.com/Sartoric/homeassistant-blueprints/blob/main/motion-light-darkness.yaml
  author: Sartoric
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          filter:
            device_class: motion
            domain: binary_sensor
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    motion_entity_luminosity:
      name: Lux threshold
      description: Threshold for the light to turn on.
      default: 7
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: lx     
    motion_condition:  
      name: Motion condition
      selector:
        entity:
          filter:
            domain: binary_sensor        
    motion_condition_value:  
      name: Motion condition value   
      selector:
        entity:
          filter:
            domain: device_state_attributes            

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"
condition:
  - condition: numeric_state
    entity_id: sensor.motion_luminosity
    below: !input motion_entity_luminosity
  - condition: state
    entity_id: !input motion_condition
    state: !input motion_condition_value
action:
  - alias: "Turn on the light"
    service: light.turn_on
    target: !input light_target
  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - alias: "Wait the number of seconds that has been set"
    delay: !input no_motion_wait
  - alias: "Turn off the light"
    service: light.turn_off
    target: !input light_target